---
title: "Hipotezių testas"
author: "Asta Kvedaraitė & Marius Survila"
date: "5/18/2020"
output: html_document
---

```{r echo = FALSE, message=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  error = TRUE,
  echo = FALSE 
)
```

# Lyginamos grupės: sveiki/sergantys ir jų amžius.
```{r}
sample <- read.csv("../output/correctedSample.csv")
age <- sample$age
alzheimer <- sample$sample
test <- t.test(age ~ alzheimer)
test$statistic[[1]]
```
Norint nustatyti sveikų ir sergančių amžiaus vidurkį, buvo atliktas T testas dviem nepriklausomoms grupėms.
Sveikų žmonių grupės amžiaus vidurkis yra `r test$estimate[[2]]`, o sergančiųjų ažmiaus vidurkis = `r test$estimate[[1]]`.
P-reikšmė = `r test$p.value`, `r test$statistic[[1]]`.

```{r}
plot(sample$age~ sample$sample, main= "Sveikų ir sergančių amžiaus pasiskirstymas", xlab = NA, ylab ="Age")

```


```{r}
if (!require("matrixTests")) install.packages("matrixTests")
if (!require("reshape2")) install.packages("reshape2")
library("matrixTests")
library(ggplot2)
library(grid)
library(gridExtra)
library(reshape2)
data <- readRDS("../output/betab.rds")
nrow(data)


dfdata <- matrixTests::row_t_onesample(data)
dfdata <- dfdata[order(dfdata$statistic, decreasing = TRUE),]
dfdata <- dfdata[1:5,]
df <- rownames(dfdata[1:5,])
df <- data[df,]
df <- as.data.frame(t(df))

df[] <- lapply(df, function(x) {
    if(is.double(x)) as.numeric(as.character(x)) else as.character(x)
})
df
df$sample <- sample$sample
sapply(df, typeof)
library(data.table)
setDT(df, keep.rownames = TRUE)[]
colnames(df)[1] <- "Sample_names"

```

```{r}

library(tidyr)
library(dplyr)
library(ggplot2)

#cg27441228,cg10925417,cg11709150,cg25753567,cg17339956
df %>% select(Sample_names,cg27441228,cg10925417,cg11709150,cg25753567,cg17339956, sample) %>%
  pivot_longer(., cols = c(cg27441228,cg10925417,cg11709150,cg25753567,cg17339956), 
               names_to = "Var", values_to = "Val") %>%
  ggplot(aes(x = Var, y = Val, color = factor(sample))) +
   geom_point() + 
  theme(axis.text.x=element_text(size=12),
        axis.text.y=element_text(size=14),
        axis.title=element_text(size=20,face="bold")) +
    labs(title = "5 Metilintos pozicijos 185 mėginiuose, turinčios didžiausius skirtumus")

```

```{r}


```