---
title: "Klasifikavimas"
author: "Asta Kvedaraitė & Marius Survila"
date: "5/27/2020"
output: html_document
---

```{r echo = FALSE, message=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  error = TRUE,
  echo = FALSE 
)
```

```{r}
library(data.table)

#Atsirenka pagal pvalue- jei metilinamos reikšmės < 0.05, tuomet patikimos
getSmaller <- function(tdata){
  tdata <- knownData
  cols <- c()
    
    names <- corrected$sample_id[corrected$sample == "Control"]
    names <- as.character(names)
    
    con <- tdata[names,]
    names <- corrected$sample_id[corrected$sample == "Alzheimer"]
    names <- as.character(names)
    alz <- tdata[names,]
    
ttest <- matrixTests::col_t_welch(alz, con)
    p <- ttest[ttest$pvalue < 0.05,]
    cols <- rownames(p)
    
  return(cols)
}

```


```{r}
getChr<- function(tdata, anno, chr){
  #chr= "chr8"
  names <- anno$Name[anno$chr == chr]
  names<- as.character(names)
  tdata <- data[names,]
  return(tdata)
}

```


```{r}

#K-kaimynai
getGroup <- function(test, known, k, val){
  names <- c()
  if (val == "pval"){
    cols <- getSmaller(known)
    known <- known[,cols]
    test <- test[,cols]
  }
  testtypes <- c()
  for (i in 1: nrow(test)){
     testing <- rbind(test[i,], known)
     d <- dist(testing,  method = "euclidean")
     m <- min(d)
     d <- as.matrix(d)
     d <- as.data.frame(d)
     d <- d[,1]
     #Mažiausi atstumai, tiek kiek k(kaimynai)
     max <- sort(d[d > 0])[1:k]
     indnames <- c()
     
     for (j in 1 : length(max)){
       ind <- which(d==max[j])[1]
       indnames[j] <- rownames(testing[ind,])
     }
     types <- c()
     #Gauti visi samples (serga/neserga pagal mėginio ID)
     for (n in 1: length(indnames)){
       types[n] <- as.character(corrected$sample[corrected$sample_id == indnames[n]])
     }
     t <- table(types)
     if (is.na(t[2]) == FALSE){
       if (t[1] > t[2]){
         testtypes[i] <- names(t[1])
       }else{
         testtypes[i] <- names(t[2])
       }
     }else{
       testtypes[i] <- names(t[1])
     }
     
  }
  #grąžina kiekvieno test mėginio spėjimą - sveikas ar sergantis
  return(testtypes)
}

```

```{r}
#Gauti reikšmes pagal ID, kokios yra teisingos(testiniams)
getTested <- function(test){
  names <- rownames(test)
  dat <- c()
  for (i in 1: length(names)){
    dat[i] <- as.character(corrected$sample[corrected$sample_id == names[1]])
  }
  return(dat)
}

```

```{r}
#gauti paklaidos reikšmę
getRate <- function(matrix, method = "s"){
  tr <- 0
  fl <- 0
  for (i in 1:nrow(matrix)){
    if (matrix$group[i] == matrix$tested[i]){
        tr <- tr+1
    }else{
      fl <- fl +1
    }
  }
  all <- fl + tr
  if (method == "f"){
    return(fl/all)
  }else {return(1-fl/all)}
}

```

```{r}
confMatrix <- function(mat, conf){
  
  for (i in 1:nrow(mat)){
     #if true then add to correct 
     if (mat$group[i] == mat$tested[i]){
        if (mat$group[i] == "Alzheimer"){conf$TrueA <- conf$TrueA + 1}
        else{conf$TrueC <- conf$TrueC + 1}
     }else{
       if (mat$group[i] == "Alzheimer"){conf$FalseA <- conf$FalseA +1}
       else{conf$FalseC <- conf$FalseC +1}
     }
  }
  return(conf)
}


```



```{r}
corrected <- read.csv("../output/correctedSample.csv")
data <- readRDS("../output/betab.rds")
anno <- readRDS("../output/annotation.rds")

```


```{r}
#Randomly shuffle the data
set.seed(2)
sample<-data[sample(nrow(data)),]

```

```{r}
#Create 10 equally size folds
#sample <- sample[1:1000,]
folds <- cut(seq(2,ncol(sample)),breaks=10, labels = FALSE)
#Perform 10 fold cross validation
frez <- c()
srez <- c()
conf <- data.frame("TrueA" = 0, "FalseA" = 0, "TrueC" = 0, "FalseC"= 0)
for(i in 1:10){
  #Segement your data by fold using the which() function 
  testIndexes <- which(folds==i,arr.ind=TRUE)
  testData <- sample[,testIndexes ]
  knownData <- sample[,-testIndexes ]

  testData <- t(testData)
  knownData <- t(knownData)
  testData <- as.data.frame(testData)
  knownData <- as.data.frame(knownData)
  #Jei paskutinis = pval, tada naudojamas t.test sumažinti duomenims
  group <- getGroup(testData, knownData, 5, "pval")
  tested <- getTested(testData)
  mat <- as.data.frame(cbind(group, tested))
  
  conf <- confMatrix(mat, conf)
  frez[i] <- getRate(mat, "f")
  srez[i] <- getRate(mat)
  
}
frez
mean(frez)
srez
mean(srez)
conf
#table(confA, confC)
```

```{r}
cdata <- getChr(data, anno, "chr8")[1:1000,]
sample<-cdata[sample(nrow(cdata)),]

folds <- cut(seq(2,ncol(sample)),breaks=10, labels = FALSE)
#Perform 10 fold cross validation
frez <- c()
srez <- c()
conf <- data.frame("TrueA" = 0, "FalseA" = 0, "TrueC" = 0, "FalseC"= 0)

for(i in 1:10){
  #Segement your data by fold using the which() function 
  testIndexes <- which(folds==i,arr.ind=TRUE)
  testData <- sample[,testIndexes ]
  knownData <- sample[,-testIndexes ]

  testData <- t(testData)
  knownData <- t(knownData)
  testData <- as.data.frame(testData)
  knownData <- as.data.frame(knownData)
  #Jei paskutinis = pval, tada naudojamas t.test sumažinti duomenims
  group <- getGroup(testData, knownData, 5, "")
  tested <- getTested(testData)
  mat <- as.data.frame(cbind(group, tested))
  conf <- confMatrix(mat, conf)
  frez[i] <- getRate(mat, "f")
  srez[i] <- getRate(mat)
  
}
mean(frez)
mean(srez)
conf
```


